commerce_shopping_hours.settings:
  type: config_object
  label: 'Commerce Shopping Hours settings'
  mapping:
    monday_from:
      type: string
      label: 'Monday'
    monday_to:
      type: string
      label: 'Monday'
    tuesday_from:
      type: string
      label: 'Tuesday'
    tuesday_to:
      type: string
      label: 'Tuesday'
    wednesday_from:
      type: string
      label: 'Wednesday'
    wednesday_to:
      type: string
      label: 'Wednesday'
    thursday_from:
      type: string
      label: 'Thursday'
    thursday_to:
      type: string
      label: 'Thursday'
    friday_from:
      type: string
      label: 'Friday'
    friday_to:
      type: string
      label: 'Friday'
    saturday_from:
      type: string
      label: 'Saturday'
    saturday_to:
      type: string
      label: 'Saturday'
    sunday_from:
      type: string
      label: 'Sunday'
    sunday_to:
      type: string
      label: 'Sunday'
    show_shopping_hours:
      type: boolean
      label: 'Show shopping hours'
    message:
      type: text
      label: 'Message'
    enable:
      type: boolean
      label: 'Enable'
